### PR TITLE
Customized to vagrant configuration.

### PR DESCRIPTION
**Pull request by partikus**
- Added instruction how to set up project.
- Added db dump.
- Changed db settings.

### CODE REVIEW

**Comment by dominikhajduk** [comment]
After migrate `baza.php` into `mail-sender.sql` :+1:

**Comment by partikus** [comment]
@dominikhajduk done

**Comment by partikus** [comment]
@php-refactor ping

**Comment by dominikhajduk** [comment]
@partikus thakd :+1:

**Comment by marcinwarzybok** [comment]
pong

**Pull request merged**
