### PR TITLE
Improve readme added composer install info

### PR DESCRIPTION
**Pull request by dominikhajduk**
@php-refactor please look on proposed changes and comment (we can merge after 2 confirmation that changes are ok)

### CODE REVIEW

**Comment by partikus** [comment]
:+1:

**Comment by PorkOne** [comment]
It's fine for me but would add more info. Maybe I'll d it later.

**Comment by partikus** [comment]
@PorkOne What info do you want add? Is sth missing?

**Comment by PorkOne** [comment]
Maybe small explanation what the command starting from 'git clone ...' really do. I'm not using terminal to work with git and don't know the clone syntax (yet ;) ).

**Comment by dominikhajduk** [comment]
@PorkOne I don't agree. For me if you don't know what command do just copy and run or read documentation.

**Comment by marcinwarzybok** [comment]
@dominikhajduk  If PorkOne want write this , we should allow it.
For me it's not necessary, but if somebody want write it..

**Comment by partikus** [comment]
@marcinwarzybok In accordance with your approach we should allow for everything,
you can create an issue with extra resource about work with git etc., but still it's out of the scope

**Comment by dominikhajduk** [comment]
@marcinwarzybok here we discuss about current PR. If @PorkOne want add something he can propose that in separate PR. In my opinion it's enough. And his comment has no details.

**Comment by mateuszmaslanka** [comment]
:+1:

**Pull request merged**
