### PR TITLE
Changes after third meeting

### PR DESCRIPTION
**Pull request by dominikhajduk**
Replace index test with dashboard test
Remove indexTest, add data provider

### CODE REVIEW

**Comment by dominikhajduk** [comment]
@php-refactor please confirm that this can be merged

**Comment by partikus** [comment]
@dominikhajduk where is the rest?

**Comment by dominikhajduk** [comment]
@partikus added missing part
@marcinwarzybok please check second part it's nit working how it should!
@php-refactor please look especially on https://github.com/dominikhajduk/mail-sender/commit/ffde705ce1d7d79b58ae0dfb27286c6da25cd49e this should be fixed before merge. Any proposal?

**Comment by marcinwarzybok** [comment]
@dominikhajduk could you prepare "todo" tests ?

**Comment by dominikhajduk** [comment]
@marcinwarzybok the list you can propose here: https://github.com/php-refactor/mail-sender/issues/8 for sure we should test:
* add mail
* add mails
* list mails
* change email content

**Comment by marcinwarzybok** [comment]
Sorry, I didn't see this commit. 

I can take :one: add mail

**Comment by partikus** [comment]
@dominikhajduk I changed test cases list to checkbox, how to do that? here [doc](https://github.com/blog/1375%0A-task-lists-in-gfm-issues-pulls-comments)

**Comment by dominikhajduk** [comment]
@php-refactor merged, without that I can not propose new PR

**Comment by partikus** [comment]
@dominikhajduk Whether this version is working?

**Comment by dominikhajduk** [comment]
@partikus I think yes. If not fixes should be proposed as PR. Without merge I can not propose any other PR. If we're waiting for any comments 2 days it's block works. I think we should discus this flow to prevent situations like that (add develop branch?). Currently presenter need wait with PR until meeting PR will be confirmed and merged.

**Comment by dominikhajduk** [comment]
@php-refactor Can we close that?

**Pull request merged**
