### PR TITLE
Add autoloader and Mail class

### PR DESCRIPTION
**Pull request by dominikhajduk**
@php-refactor after meeting 4 if no typo we can merge as a base for master branch pull request commit

### CODE REVIEW

**Comment by partikus** [comment]
@dominikhajduk could you create an extra PR for autoloader fix (to master branch)?

**Comment by dominikhajduk** [comment]
@partikus sure please look on https://github.com/php-refactor/mail-sender/pull/23

**Comment by partikus** [comment]
@dominikhajduk rebase pls

**Comment by dominikhajduk** [comment]
@partikus rebased. I think. Is rebase presented somehow in history?

**Pull request closed without merging**
