### PR TITLE
Changes after second meeting.

### PR DESCRIPTION
**Pull request by partikus**
Added composer
Added PHPUnit
Moved public php files to 'web' directory
Added first functional test

### CODE REVIEW

**Comment by partikus** [comment]
@php-refactor

**Comment by partikus** [comment]
@dominikhajduk done, I've changed the order
@php-refactor code review pls

**Comment by dominikhajduk** [comment]
@partikus thanks

**Comment by dominikhajduk** [comment]
@php-refactor please look on this today it would be nice to merge. If you think that's ok then also please let us know

**Comment by partikus** [comment]
@dominikhajduk ping @php-refactor

**Comment by dominikhajduk** [comment]
@php-refactor should we run test with some flag? after run:
`bin/phpunit -c phpunit.xml --debug`
I'm getting:
```
PHPUnit 4.8.6 by Sebastian Bergmann and contributors.

Starting test 'IndexTest::testTitle'.
S

Time: 2.99 seconds, Memory: 4.50Mb

OK, but incomplete, skipped, or risky tests!
Tests: 1, Assertions: 0, Skipped: 1.
```

**Comment by partikus** [comment]
@dominikhajduk Could you run ``bin/phpunit -c --verbose --debug phpunit.xml tests/functional/IndexTest.php`` and send us the output ?

**Comment by dominikhajduk** [comment]
```
vagrant@vagrant-ubuntu-trusty-64:/var/www/mail-sender$ bin/phpunit -c phpunit.xml tests/functional/IndexTest.php --verbose --debug
PHPUnit 4.8.6 by Sebastian Bergmann and contributors.

Runtime:	PHP 5.6.13-1+deb.sury.org~trusty+3
Configuration:	/var/www/mail-sender/phpunit.xml


Starting test 'IndexTest::testTitle'.
S

Time: 2.75 seconds, Memory: 4.50Mb

There was 1 skipped test:

1) IndexTest::testTitle
The Selenium Server is not active on host 127.0.0.1 at port 4444.

OK, but incomplete, skipped, or risky tests!
Tests: 1, Assertions: 0, Skipped: 1.
```
Should I halt machine and run vagrant provision?

**Comment by partikus** [comment]
@dominikhajduk try to restart selenium running ``sudo service selenium restart`` and let us know if it helps

**Pull request merged**
